<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="MediaContext.cs" />
    <Compile Remove="Repositories\MediaRepo.cs" />
    <Compile Remove="UnitOfWork\MediaUnit.cs" />
  </ItemGroup>

	<ItemGroup>
		<AssemblyAttribute Include="System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverageAttribute" />
	</ItemGroup>

	<ItemGroup>
	  <ProjectReference Include="..\Entities\Entities.csproj" />
	</ItemGroup>

</Project>
