# Deploy to Azure Kubernetes Service
# Build and push image to Azure Container Registry; Deploy to Azure Kubernetes Service
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
  branches:
    include:
    - dev
  paths:
    include:
    - 'MicroServices/Media/*'
    exclude:
    - '**/*.md'
    - '**/nuget.config'

variables:
- template: ${{variables['System.DefaultWorkingDirectory']}}/MicroServices/Media/build-deploy/variables/pipeline-variables.yml
- name: version
  value: '1.0.0'
- name: tag # <version>.<buildnumber>.<commit-id>
  value: "$(version).$(Build.BuildNumber).$(Build.SourceVersion)"

stages:
- template: ${{variables['System.DefaultWorkingDirectory']}}/Shared/deploy/full-deploy/template-stage-all-environment-deploy.yml