<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
	  <Protobuf Include="Protos\order.proto" GrpcServices="Server" AdditionalImportDirs="Protos\" />
	  <Protobuf Include="Protos\order_detail.proto" GrpcServices="Server" AdditionalImportDirs="Protos\" />
	  <Protobuf Include="Protos\product.proto" GrpcServices="Server" AdditionalImportDirs="Protos\" />
	  <Protobuf Include="Protos\decimal_value.proto" GrpcServices="Server" AdditionalImportDirs="Protos\" />
	  
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Grpc.AspNetCore" Version="2.40.0" />
    <PackageReference Include="Grpc.AspNetCore.Server.Reflection" Version="2.50.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\RepositoryDapper\RepositoryDapper.csproj" />
  </ItemGroup>

</Project>
