<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Models\Request\**" />
    <EmbeddedResource Remove="Models\Request\**" />
    <None Remove="Models\Request\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="TXC.Common.Domain" Version="2.0.0" />
    <PackageReference Include="TXC.Proto.Credit" Version="2.0.0.4" />
	<PackageReference Include="Z.Dapper.Plus" Version="4.0.36" />
	<PackageReference Include="Dapper.Contrib" Version="2.0.78" />
  </ItemGroup>

</Project>
