<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
	<RootNamespace>TXC.Proto.Media</RootNamespace>
	<PackageId>TXC.Proto.Media</PackageId>
	<Version>2.0.0.0</Version>
	<Authors>Edenred</Authors>
	<Description>Media Proto</Description>
	<IsPackable>true</IsPackable>
	<GeneratePackageOnBuild>true</GeneratePackageOnBuild>	  
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Google.Protobuf" Version="3.21.5" />
    <PackageReference Include="Grpc.AspNetCore" Version="2.47.0" />
    <PackageReference Include="Grpc.Tools" Version="2.48.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

	<ItemGroup>
		<Protobuf Include="Protos\common.proto" GrpcServices="Server,Client">
		</Protobuf>
		<Protobuf Include="Protos\media.proto" GrpcServices="Server,Client" AdditionalImportDirs="Protos\" />
	</ItemGroup>	

</Project>
